services:
  llm_server:
    build:
      context: ./llm_server
    ports:
      - "8000:8000"
    environment:
      - HF_HOME=/root/.cache/huggingface
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    volumes:
      - /home/tf/.cache/huggingface/hub:/root/.cache/huggingface/hub
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      retries: 10
      start_period: 10s
      timeout: 3s
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  discord_bot:
    build: ./discord_bot
    depends_on:
      llm_server:
        condition: service_healthy
    environment:
      - DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}
