services:
  llm_server:
    build:
      context: ./llm_server
    ports:
      - "8000:8000"
    container_name: llm_server
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility


  discord_bot:
    build: ./discord_bot
    container_name: discord_bot
    depends_on:
      - llm_server

